### ISSUE TITLE
Missing Favicon on Website

### ISSUE THREAD

**Issue by ayushsingh199** [bhavy3103/BMark-ECommerce#1]
#### Description
The website is missing a favicon, which results in an empty or generic icon being displayed on the browser tab. Adding a favicon is important for branding and providing a polished user experience.

#### Expected Behavior
A favicon should be visible in the browser tab, representing the brand or website. This improves the overall user experience and makes the website easier to identify among multiple open tabs.

#### Actual Behavior
No favicon is currently displayed, leaving a default browser icon in its place.

#### Steps to Reproduce
1. Open the website in any browser.
2. Observe the browser tab — there is no favicon displayed.
<img width="475" alt="Screenshot 2024-10-16 at 12 15 25 AM" src="https://github.com/user-attachments/assets/e0c3391e-564c-4ff9-a13f-5a50e8170d96">

**Comment by ayushsingh199** [comment]
please assign this issue to me!

**Comment by acenasir** [comment]
please assign this issue to me

**Comment by bhavy3103** [comment]
![image](https://github.com/user-attachments/assets/85134b5b-73df-40b2-a586-d257cf3ebbdc)

@ayushsingh199 use above image as a favicon

**Comment by ayushsingh199** [comment]
okay sir noted!
