### ISSUE TITLE
Implement search feature to find particular product by its name

### ISSUE THREAD

**Issue by Shreya-1305** [bhavy3103/BMark-ECommerce#11]
I want to add search feature to search for the products.

**Comment by bhavy3103** [comment]
@Shreya-1305 It is already working but it is not showing just because of a lack of inventory right now 
![image](https://github.com/user-attachments/assets/1b334a38-3ad0-40bc-9e63-5320ab720fb0)

**Comment by Shreya-1305** [comment]
Okay @bhavy3103
