### ISSUE TITLE
Avoid multiple Login submits

### ISSUE THREAD

**Issue by karthik-script** [bhavy3103/BMark-ECommerce#16]
Hi @bhavy3103 , I can fix this issue for you. Please assign it to me. Thanks.

Description:
When a user attempts to log in, if the login button is clicked multiple times in quick succession, multiple submit requests are triggered. This can lead to redundant requests being sent to the server, possibly causing performance issues or duplicate logins.

Steps to Reproduce:

	1.	Navigate to the login page.
	2.	Enter valid login credentials.
	3.	Click the “Login” button multiple times in quick succession.
	4.	Observe multiple submit requests being sent.

Expected Behavior:
Only one login submit request should be sent, even if the user clicks the “Login” button multiple times.

Current Behavior:
Multiple requests are sent if the “Login” button is clicked repeatedly.

Proposed Solution:
Disable the “Login” button and show a loading state after the first submit until the login process is complete.

**Comment by karthik-script** [comment]
Hi @bhavy3103 , Here is the PR. Please take a look. Thanks.
https://github.com/bhavy3103/BMark-ECommerce/pull/23

**Comment by vllmstl** [comment]
Hi @bhavy3103 , can you please add Labels on this for Hactoberfest? Thanks.
