### ISSUE TITLE
[ENHANCEMENT] navbar animation for dropdown and save, cart buttons

### ISSUE THREAD

**Issue by ashish-um** [bhavy3103/BMark-ECommerce#19]
clicking the navbar dropdown, show the dropdown items very abruptly without any animation, same is with save, cart button.

Hey @bhavy3103  Please assign this task to me so that I can start working on it.
If there is any preference from your side, please tell me.
And also don't forget to add Labels on this for **_Hactoberfest_**

**Comment by bhavy3103** [comment]
okay, let's see your creativity do as much as you want but make sure it is related to the whole theme.
