### ISSUE TITLE
[chore] re-word the subscription section

### ISSUE THREAD

**Issue by CynthiaWahome** [bhavy3103/BMark-ECommerce#56]
Hi @bhavy3103,
Please assign me to reword the subscription section for a Hacktoberfest 2024 contribution.

from **Subscribe us for get news events and offers**
to  **Subscribe to receive the latest news, events, and exclusive offers.**

**Comment by bhavy3103** [comment]
how you provide the latest news like in which formate mail, notification, etc. Can you elaborate a little bit more?

**Comment by CynthiaWahome** [comment]
Hi @bhavy3103 
I meant rewording this part to instead read...**Subscribe to receive the latest news, events, and exclusive offers.**
![image](https://github.com/user-attachments/assets/23e45c03-bd21-4735-8ed4-2600b92484be)

**Comment by bhavy3103** [comment]
okay, is it needed?

**Comment by CynthiaWahome** [comment]
Hi @bhavy3103 

Thanks for your reply! While it might seem like a small tweak, rewording the subscription section could enhance the overall user experience. Clear and professional language makes a website feel more polished and approachable, which is important for creating a pleasant UI/UX experience.

This change can also serve as a good first issue for Hacktoberfest, as it would allow me to get involved in improving the project’s design and copywriting without making any significant code modifications.

Let me know what you think!

Best regards,
Cynthia

**Comment by bhavy3103** [comment]
okay, show your creativity...
