### ISSUE TITLE
[chore] : Update Item Labels to Sentence Case for Consistency

### ISSUE THREAD

**Issue by CynthiaWahome** [bhavy3103/BMark-ECommerce#57]
Hi @bhavy3103,
Could we update the casing of "hoodie marshmello hoodie and mac book" to sentence case for consistency with the other items?

from **hoodie marshmello hoodie and mac book**
to **Hoodie Marshmello Hoodie and Mac Book**

Please assign this to be for a Hacktoberfest submission, thanks!
![image](https://github.com/user-attachments/assets/da3eb8c7-ac5b-4bce-8983-3af386863ef7)

**Comment by bhavy3103** [comment]
Yes, Thank you for addressing this issue. But the Item name update right only have BMark due to RBAC.
I will solve this.

**Comment by CynthiaWahome** [comment]
Hi @bhavy3103 
See the red highlight in the screenshot attached.

Its changing the case so that instead of  **hoodie marshmello hoodie and mac book** we have it as **Hoodie Marshmello Hoodie and Mac Book**

Do you see the difference?

![png](https://github.com/user-attachments/assets/135cbbd9-df81-4750-861f-2244ab57377a)

**Comment by bhavy3103** [comment]
yes, I can see but I am telling you that name can be changed only by the BMark Store owner.
So I can't assign it you.

**Comment by bhavy3103** [comment]
It will be updated soon thank you for your response.
