### ISSUE TITLE
Update logo X

### ISSUE THREAD

**Issue by Priyanshu-su30** [bhavy3103/BMark-ECommerce#65]
The twitter bird logo needs update to X logo
![Screenshot (251)](https://github.com/user-attachments/assets/639ca923-f8d6-4f14-812e-bee667df4fde)

Assign me this task and I'll Work on it under the label of Hacktoberfest

**Comment by kartik-212004** [comment]
I would like to resolve this issue. Please assign it to me.
Thanks
